{
  "openapi": "3.0.0",
  "info": {
    "title": "NOVA New User Onboarding - v1",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://example.com",
      "variables": {}
    }
  ],
  "paths": {
    "/accounts/{accountNumber}/statement/latest": {
      "get": {
        "tags": [
          "Statement"
        ],
        "summary": "Latest",
        "operationId": "Latest",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "example": "{\n    \"period\": \"latest\",\n    \"balance\": {\n        \"opening\": 948.75,\n        \"closing\": 97.64\n    },\n    \"money\": {\n        \"in\": 579.16,\n        \"out\": 66.24\n    },\n    \"transactions\": [\n        {\n            \"date\": \"Tue Nov 02 2021 01:01:26 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Jacobson, Jast and Rice\",\n            \"type\": \"deposit\",\n            \"amount\": 366.11,\n            \"balance\": 943.21\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 10:54:38 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Kris Inc\",\n            \"type\": \"withdrawal\",\n            \"amount\": 179.08,\n            \"balance\": 927.73\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 02:53:15 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Hane LLC\",\n            \"type\": \"payment\",\n            \"amount\": 370.67,\n            \"balance\": 980.34\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 20:36:45 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Durgan LLC\",\n            \"type\": \"payment\",\n            \"amount\": 920.86,\n            \"balance\": 346.47\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 04:17:40 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Maggio and Sons\",\n            \"type\": \"deposit\",\n            \"amount\": 267.91,\n            \"balance\": 437.16\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 14:11:03 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Lind, Wehner and Pfannerstill\",\n            \"type\": \"invoice\",\n            \"amount\": 43.53,\n            \"balance\": 689.27\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 14:09:22 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Heller, Wisozk and Davis\",\n            \"type\": \"payment\",\n            \"amount\": 799.75,\n            \"balance\": 992.57\n        },\n        {\n            \"date\": \"Mon Nov 01 2021 22:29:28 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Kertzmann, Breitenberg and Zieme\",\n            \"type\": \"invoice\",\n            \"amount\": 353.61,\n            \"balance\": 400.98\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 00:02:59 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Nienow Inc\",\n            \"type\": \"withdrawal\",\n            \"amount\": 485.80,\n            \"balance\": 476.17\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 13:03:26 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Cronin - Pollich\",\n            \"type\": \"withdrawal\",\n            \"amount\": 248.50,\n            \"balance\": 955.25\n        }\n    ]\n}"
                },
                "example": "{\n    \"period\": \"latest\",\n    \"balance\": {\n        \"opening\": 592.00,\n        \"closing\": 850.86\n    },\n    \"money\": {\n        \"in\": 738.29,\n        \"out\": 166.95\n    },\n    \"transactions\": [\n        {\n            \"date\": \"Tue Nov 02 2021 03:12:59 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Schroeder LLC\",\n            \"type\": \"invoice\",\n            \"amount\": 472.23,\n            \"balance\": 975.82\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 07:25:47 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Douglas LLC\",\n            \"type\": \"withdrawal\",\n            \"amount\": 579.54,\n            \"balance\": 478.19\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 03:15:25 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Schimmel, Veum and Ernser\",\n            \"type\": \"payment\",\n            \"amount\": 183.96,\n            \"balance\": 930.73\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 10:23:17 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Haley, Gislason and Yundt\",\n            \"type\": \"invoice\",\n            \"amount\": 41.48,\n            \"balance\": 725.33\n        },\n        {\n            \"date\": \"Mon Nov 01 2021 22:39:10 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Harris, Hegmann and Sawayn\",\n            \"type\": \"deposit\",\n            \"amount\": 879.64,\n            \"balance\": 646.98\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 01:31:45 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Jacobson, Monahan and Roberts\",\n            \"type\": \"withdrawal\",\n            \"amount\": 582.72,\n            \"balance\": 849.03\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 19:06:42 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Vandervort Group\",\n            \"type\": \"invoice\",\n            \"amount\": 12.65,\n            \"balance\": 522.66\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 03:08:30 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Smitham LLC\",\n            \"type\": \"withdrawal\",\n            \"amount\": 279.13,\n            \"balance\": 781.56\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 03:46:15 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Moore LLC\",\n            \"type\": \"withdrawal\",\n            \"amount\": 723.63,\n            \"balance\": 544.53\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 04:53:24 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Predovic - Ferry\",\n            \"type\": \"invoice\",\n            \"amount\": 673.55,\n            \"balance\": 638.57\n        }\n    ]\n}"
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/accounts/{accountNumber}/statement/date": {
      "get": {
        "tags": [
          "Statement"
        ],
        "summary": "Date",
        "operationId": "Date",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Mon, 14 Jun 2021 14:30:25 GMT"
                  }
                }
              },
              "Transfer-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "chunked"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "close"
                  }
                }
              },
              "Server": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "nginx"
                  }
                }
              },
              "x-srv-trace": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "v=1;t=d33d68b932344fce"
                  }
                }
              },
              "x-srv-span": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "v=1;s=210e5b055e5bd71e"
                  }
                }
              },
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "X-RateLimit-Limit": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "120"
                  }
                }
              },
              "X-RateLimit-Remaining": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "119"
                  }
                }
              },
              "X-RateLimit-Reset": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "1623681083"
                  }
                }
              },
              "ETag": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "W/\"96-S/5iQ2y1qqIInh5BwoPc+chvDJU\""
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Content-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "gzip"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "string",
                  "example": "{\n    \"period\": {\n        \"from\": \"Tue Oct 05 2021 14:44:37 GMT-0400 (Eastern Daylight Time)\",\n        \"to\": \"Mon Nov 01 2021 21:12:44 GMT-0400 (Eastern Daylight Time)\"\n    },\n    \"balance\": {\n        \"opening\": 383.54,\n        \"closing\": 599.95\n    },\n    \"money\": {\n        \"in\": 262.94,\n        \"out\": 300.35\n    },\n    \"transactions\": [\n        {\n            \"date\": \"Tue Nov 02 2021 04:02:13 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Lang - Upton\",\n            \"type\": \"invoice\",\n            \"amount\": 470.74,\n            \"balance\": 254.28\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 02:07:19 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Hayes, Wolf and Nolan\",\n            \"type\": \"payment\",\n            \"amount\": 864.14,\n            \"balance\": 982.30\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 03:29:13 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Haag - Simonis\",\n            \"type\": \"payment\",\n            \"amount\": 474.15,\n            \"balance\": 786.01\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 06:42:06 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Heller, Kulas and Mayer\",\n            \"type\": \"invoice\",\n            \"amount\": 760.99,\n            \"balance\": 440.94\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 11:55:00 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Simonis, Parisian and Feeney\",\n            \"type\": \"invoice\",\n            \"amount\": 768.19,\n            \"balance\": 406.34\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 02:50:12 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Lowe LLC\",\n            \"type\": \"payment\",\n            \"amount\": 699.32,\n            \"balance\": 901.78\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 11:25:17 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Will, Quitzon and Ortiz\",\n            \"type\": \"payment\",\n            \"amount\": 548.26,\n            \"balance\": 637.18\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 09:59:38 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Walker, Hills and Bosco\",\n            \"type\": \"deposit\",\n            \"amount\": 234.56,\n            \"balance\": 854.73\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 02:37:57 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Pollich - Hegmann\",\n            \"type\": \"withdrawal\",\n            \"amount\": 642.91,\n            \"balance\": 175.17\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 03:21:36 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Weimann - Boyer\",\n            \"type\": \"payment\",\n            \"amount\": 823.91,\n            \"balance\": 993.97\n        }\n    ]\n}"
                },
                "example": "{\n    \"period\": {\n        \"from\": \"Mon Sep 20 2021 16:52:45 GMT-0400 (Eastern Daylight Time)\",\n        \"to\": \"Tue Nov 02 2021 15:13:01 GMT-0400 (Eastern Daylight Time)\"\n    },\n    \"balance\": {\n        \"opening\": 852.93,\n        \"closing\": 659.37\n    },\n    \"money\": {\n        \"in\": 162.03,\n        \"out\": 416.14\n    },\n    \"transactions\": [\n        {\n            \"date\": \"Mon Nov 01 2021 21:22:46 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Rutherford, Kuhn and Davis\",\n            \"type\": \"payment\",\n            \"amount\": 550.45,\n            \"balance\": 812.41\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 17:54:35 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Steuber, Bosco and Aufderhar\",\n            \"type\": \"withdrawal\",\n            \"amount\": 352.28,\n            \"balance\": 805.94\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 00:32:22 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Murray, Lind and Conn\",\n            \"type\": \"withdrawal\",\n            \"amount\": 750.29,\n            \"balance\": 380.53\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 16:08:41 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Ortiz - Strosin\",\n            \"type\": \"withdrawal\",\n            \"amount\": 907.48,\n            \"balance\": 911.39\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 01:54:43 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Lockman - Abbott\",\n            \"type\": \"withdrawal\",\n            \"amount\": 488.83,\n            \"balance\": 27.05\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 20:56:06 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Thiel, Labadie and Fay\",\n            \"type\": \"withdrawal\",\n            \"amount\": 699.06,\n            \"balance\": 494.85\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 01:03:02 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Mosciski - Rutherford\",\n            \"type\": \"invoice\",\n            \"amount\": 709.30,\n            \"balance\": 280.79\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 06:03:08 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Gaylord and Sons\",\n            \"type\": \"deposit\",\n            \"amount\": 948.75,\n            \"balance\": 410.76\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 11:01:22 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Heaney LLC\",\n            \"type\": \"withdrawal\",\n            \"amount\": 226.07,\n            \"balance\": 562.89\n        },\n        {\n            \"date\": \"Tue Nov 02 2021 05:15:39 GMT-0400 (Eastern Daylight Time)\",\n            \"description\": \"Torphy Inc\",\n            \"type\": \"payment\",\n            \"amount\": 848.31,\n            \"balance\": 402.62\n        }\n    ]\n}"
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/accounts/create": {
      "post": {
        "tags": [
          "Accounts"
        ],
        "summary": "Create",
        "operationId": "Create",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRequest"
              },
              "example": {
                "type": "Checking Account",
                "holder": "{{customerId}}"
              }
            }
          },
          "required": true
        },
        "responses": {
          "default": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200OK"
                },
                "example": {
                  "type": "Savings Account",
                  "details": {
                    "domestic": {
                      "account": "16088994",
                      "routing": "84768721"
                    },
                    "international": {
                      "bic": "RLOOLSY1",
                      "iban": "LB417006B8554854OI3499112308"
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/accounts/{accountNumber}/overview": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Overview",
        "operationId": "Overview",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "example": "{\n    \"type\": \"Investment Account\",\n    \"balance\": {\n        \"available\": 819.18,\n        \"present\": 108.06\n    },\n    \"details\": {\n        \"domestic\": {\n            \"account\": \"79199523\",\n            \"routing\": \"74914016\"\n        },\n        \"international\": {\n            \"bic\": \"IGVAANV1172\",\n            \"iban\": \"MC2501229300942540LJ8358092\"\n        }\n    },\n    \"interestRate\": 0.01,\n    \"lastStatementDate\": \"Tue Nov 02 2021 10:15:22 GMT-0400 (Eastern Daylight Time)\"\n}"
                },
                "example": "{\n    \"type\": \"Personal Loan Account\",\n    \"balance\": {\n        \"available\": 632.22,\n        \"present\": 339.71\n    },\n    \"details\": {\n        \"domestic\": {\n            \"account\": \"49114539\",\n            \"routing\": \"11252386\"\n        },\n        \"international\": {\n            \"bic\": \"GBHULVJ1\",\n            \"iban\": \"CH8572759176K0032S830\"\n        }\n    },\n    \"interestRate\": 0.01,\n    \"lastStatementDate\": \"Tue Nov 02 2021 10:12:14 GMT-0400 (Eastern Daylight Time)\"\n}"
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/create": {
      "post": {
        "tags": [
          "Create"
        ],
        "summary": "New user",
        "description": "Creates a new user in the system. The user will be assigned an ID automatically. This can be found in the response.",
        "operationId": "Newuser",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "firstName",
                  "lastName"
                ],
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string",
                    "description": "The user's first name (required)",
                    "example": "Kaley"
                  },
                  "lastName": {
                    "type": "string",
                    "description": "The user's last name (required)",
                    "example": "Klein"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Express"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "101"
                  }
                }
              },
              "ETag": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "W/\"65-KsPJ95rCxmmvvRBY2Sqroxk2vmA\""
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Thu, 10 Jan 2019 23:58:59 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/Newuser"
                },
                "example": {
                  "status": "success",
                  "firstName": "Ben",
                  "lastName": "Smith",
                  "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/get": {
      "get": {
        "tags": [
          "Read"
        ],
        "summary": "Retrieve all users",
        "description": "Get all users in the system.",
        "operationId": "Getallusers",
        "parameters": [
          {
            "name": "all",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "boolean",
              "example": true
            }
          },
          {
            "name": "key",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{key}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Express"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "105"
                  }
                }
              },
              "ETag": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "W/\"69-ti7ujd/Cyb8EeoWoqRXh482Zy5o\""
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Fri, 11 Jan 2019 00:00:53 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/200OK1"
                  },
                  "description": "",
                  "example": [
                    {
                      "status": "success"
                    },
                    {
                      "firstName": "Ben",
                      "lastName": "Smith",
                      "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
                    }
                  ]
                },
                "example": [
                  {
                    "status": "success"
                  },
                  {
                    "firstName": "Ben",
                    "lastName": "Smith",
                    "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
                  }
                ]
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/update": {
      "put": {
        "tags": [
          "Update"
        ],
        "summary": "Update user",
        "description": "Send the keys that you'd like to update, this can be one or more of `firstName`, `lastName` and `password`.",
        "operationId": "Updateuser",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "The user's ID (required)",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "{{id}}"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "firstName"
                ],
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string",
                    "description": "The user's new first name",
                    "example": "Benjamin"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Express"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "106"
                  }
                }
              },
              "ETag": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "W/\"6a-SA9mzR+M2pmN7WPGgLm1ZqtRYis\""
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Fri, 11 Jan 2019 00:18:07 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/Updateuser"
                },
                "example": {
                  "status": "success",
                  "firstName": "Benjamin",
                  "lastName": "Smith",
                  "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/delete": {
      "delete": {
        "tags": [
          "Delete"
        ],
        "summary": "Delete user",
        "description": "Deletes a user from the system by `id`.",
        "operationId": "Deleteuser",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "The user's ID",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "{{id}}"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "text/plain"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Express"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "64"
                  }
                }
              },
              "ETag": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "W/\"40-bT/ASzl0KO3wj/eo2xEBaHPLnvk\""
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Fri, 11 Jan 2019 00:20:55 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/Deleteuser"
                },
                "example": {
                  "status": "success",
                  "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/payments/{accountNumber}/payees": {
      "get": {
        "tags": [
          "Payees"
        ],
        "summary": "List",
        "operationId": "List",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "example": "[\n    {\n        \"name\": \"Ralph Hintz\",\n        \"checking\": 64429926,\n        \"routing\": 24799195\n    },\n    {\n        \"name\": \"Vivian Ratke\",\n        \"checking\": 72080701,\n        \"routing\": 62430643\n    },\n    {\n        \"name\": \"Donald Bergstrom\",\n        \"checking\": 56602499,\n        \"routing\": 37700265\n    },\n    {\n        \"name\": \"Jermaine Kemmer\",\n        \"checking\": 85797715,\n        \"routing\": 57712945\n    },\n    {\n        \"name\": \"Christina Gutkowski\",\n        \"checking\": 68455947,\n        \"routing\": 86742731\n    },\n    {\n        \"name\": \"Janice Barrows\",\n        \"checking\": 71960627,\n        \"routing\": 66940110\n    },\n    {\n        \"name\": \"Abraham Hessel\",\n        \"checking\": 47339139,\n        \"routing\": 08373590\n    },\n    {\n        \"name\": \"Eric Pfeffer\",\n        \"checking\": 57936619,\n        \"routing\": 99144481\n    },\n    {\n        \"name\": \"Georgia Roberts\",\n        \"checking\": 39813193,\n        \"routing\": 52216169\n    },\n    {\n        \"name\": \"Devin Bergnaum\",\n        \"checking\": 34211405,\n        \"routing\": 11830641\n    }\n]"
                },
                "example": "[\n    {\n        \"name\": \"Alejandro Reichert\",\n        \"checking\": 49519513,\n        \"routing\": 41858408\n    },\n    {\n        \"name\": \"Sandy Funk\",\n        \"checking\": 89056703,\n        \"routing\": 49713129\n    },\n    {\n        \"name\": \"Aaron Metz\",\n        \"checking\": 09806437,\n        \"routing\": 55100334\n    },\n    {\n        \"name\": \"Darrell Bauch\",\n        \"checking\": 85125097,\n        \"routing\": 09173516\n    },\n    {\n        \"name\": \"Isaac Feil\",\n        \"checking\": 20270828,\n        \"routing\": 35365127\n    },\n    {\n        \"name\": \"Leigh Rohan\",\n        \"checking\": 90142633,\n        \"routing\": 00431026\n    },\n    {\n        \"name\": \"Melody Ryan\",\n        \"checking\": 43478216,\n        \"routing\": 23899846\n    },\n    {\n        \"name\": \"Howard Gorczany\",\n        \"checking\": 22511905,\n        \"routing\": 01385400\n    },\n    {\n        \"name\": \"Rudy Hackett\",\n        \"checking\": 56305325,\n        \"routing\": 27537298\n    },\n    {\n        \"name\": \"Denise Corkery\",\n        \"checking\": 90846626,\n        \"routing\": 84234984\n    }\n]"
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/payments/{accountNumber}/payees/add": {
      "post": {
        "tags": [
          "Payees"
        ],
        "summary": "Add",
        "operationId": "Add",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "text/plain": {
              "schema": {
                "type": "string",
                "example": "{\n    \"name\": \"Hilda Kirlin II\",\n    \"checking\": 46744442,\n    \"routing\": 93450896\n}"
              },
              "example": "{\n    \"name\": \"Andrea Harber\",\n    \"checking\": 63436544,\n    \"routing\": 67511746\n}"
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200OK2"
                },
                "example": {
                  "payeeId": "144826f8-43cf-4c78-a604-9f53fccec819"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/payments/{accountNumber}/limits": {
      "get": {
        "tags": [
          "Limits"
        ],
        "summary": "Current",
        "operationId": "Current",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200OK3"
                },
                "example": {
                  "daily": 30000
                }
              }
            }
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": [
          "Limits"
        ],
        "summary": "Update",
        "operationId": "Update",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest"
              },
              "example": {
                "daily": 30000
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200OK4"
                },
                "example": {
                  "status": "success"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/payments/{accountNumber}/transfer": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Transfer",
        "operationId": "Transfer",
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransferRequest"
              },
              "example": {
                "payeeId": "eea58966-aff3-4631-aefe-a6247b4be10d",
                "amount": "184.92",
                "reference": "Aut id aliquid.",
                "date": "Mon Nov 01 2021 23:21:49 GMT-0400 (Eastern Daylight Time)"
              }
            }
          },
          "required": true
        },
        "responses": {
          "default": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200OK5"
                },
                "example": {
                  "transaction": "complete"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "CreateRequest": {
        "title": "CreateRequest",
        "required": [
          "type",
          "holder"
        ],
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "holder": {
            "type": "string"
          }
        },
        "example": {
          "type": "Money Market Account",
          "holder": "{{customerId}}"
        }
      },
      "200OK": {
        "title": "200OK",
        "required": [
          "type",
          "details"
        ],
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/Details"
          }
        },
        "example": {
          "type": "Home Loan Account",
          "details": {
            "domestic": {
              "account": "10087447",
              "routing": "06632273"
            },
            "international": {
              "bic": "TLREBZT1777",
              "iban": "FO1600796009844995"
            }
          }
        }
      },
      "Details": {
        "title": "Details",
        "required": [
          "domestic",
          "international"
        ],
        "type": "object",
        "properties": {
          "domestic": {
            "$ref": "#/components/schemas/Domestic"
          },
          "international": {
            "$ref": "#/components/schemas/International"
          }
        },
        "example": {
          "domestic": {
            "account": "11051410",
            "routing": "38178420"
          },
          "international": {
            "bic": "TCSIGBL1",
            "iban": "NL62LTDE2200137659"
          }
        }
      },
      "Domestic": {
        "title": "Domestic",
        "required": [
          "account",
          "routing"
        ],
        "type": "object",
        "properties": {
          "account": {
            "type": "string"
          },
          "routing": {
            "type": "string"
          }
        },
        "example": {
          "account": "19904561",
          "routing": "78022041"
        }
      },
      "International": {
        "title": "International",
        "required": [
          "bic",
          "iban"
        ],
        "type": "object",
        "properties": {
          "bic": {
            "type": "string"
          },
          "iban": {
            "type": "string"
          }
        },
        "example": {
          "bic": "IKBOUSU1",
          "iban": "TR650428402627307722138001"
        }
      },
      "Newuser": {
        "title": "Newuser",
        "required": [
          "status",
          "firstName",
          "lastName",
          "id"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "example": {
          "status": "success",
          "firstName": "Ben",
          "lastName": "Smith",
          "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
        }
      },
      "200OK1": {
        "title": "200OK1",
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "example": {
          "status": "success"
        }
      },
      "GetuserbyID": {
        "title": "GetuserbyID",
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "example": {
          "status": "success"
        }
      },
      "GetuserbyID(nouserfound)": {
        "title": "GetuserbyID(nouserfound)",
        "required": [
          "status",
          "id"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "example": {
          "status": "no user found",
          "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b"
        }
      },
      "m200": {
        "title": "m200",
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "example": {
          "status": "success"
        }
      },
      "Updateuser": {
        "title": "Updateuser",
        "required": [
          "status",
          "firstName",
          "lastName",
          "id"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "example": {
          "status": "success",
          "firstName": "Benjamin",
          "lastName": "Smith",
          "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
        }
      },
      "Deleteuser": {
        "title": "Deleteuser",
        "required": [
          "status",
          "id"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "example": {
          "status": "success",
          "id": "0729d37c-ef9f-4ffa-8f71-a6eedf1f95b7"
        }
      },
      "200OK2": {
        "title": "200OK2",
        "required": [
          "payeeId"
        ],
        "type": "object",
        "properties": {
          "payeeId": {
            "type": "string"
          }
        },
        "example": {
          "payeeId": "c1d38c15-5b55-4b14-809d-23d57daea679"
        }
      },
      "200OK3": {
        "title": "200OK3",
        "required": [
          "daily"
        ],
        "type": "object",
        "properties": {
          "daily": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "daily": 30000
        }
      },
      "UpdateRequest": {
        "title": "UpdateRequest",
        "required": [
          "daily"
        ],
        "type": "object",
        "properties": {
          "daily": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "daily": 30000
        }
      },
      "200OK4": {
        "title": "200OK4",
        "required": [
          "status"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          }
        },
        "example": {
          "status": "success"
        }
      },
      "TransferRequest": {
        "title": "TransferRequest",
        "required": [
          "payeeId",
          "amount",
          "reference",
          "date"
        ],
        "type": "object",
        "properties": {
          "payeeId": {
            "type": "string"
          },
          "amount": {
            "type": "string"
          },
          "reference": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        },
        "example": {
          "payeeId": "8eb4d39a-95da-45c4-a66b-bb871a7073e1",
          "amount": "45.27",
          "reference": "Enim necessitatibus quasi ipsam quo illo.",
          "date": "Tue Nov 02 2021 01:28:59 GMT-0400 (Eastern Daylight Time)"
        }
      },
      "200OK5": {
        "title": "200OK5",
        "required": [
          "transaction"
        ],
        "type": "object",
        "properties": {
          "transaction": {
            "type": "string"
          }
        },
        "example": {
          "transaction": "complete"
        }
      }
    }
  },
  "tags": [
    {
      "name": "Statement"
    },
    {
      "name": "Accounts"
    },
    {
      "name": "Create"
    },
    {
      "name": "Read"
    },
    {
      "name": "Update"
    },
    {
      "name": "Delete"
    },
    {
      "name": "Payees"
    },
    {
      "name": "Limits"
    },
    {
      "name": "Payments"
    }
  ]
}